MCC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] 

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name='home'), 
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('add-people/', views.add_people, name="add_people"),
    path('add-todo/', views.add_todo, name="add_todo"),
    path('todos-page/', views.todos_page, name="todos_page"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


def user_directory_path(instance, filename):
    return 'uploads/{0}/{1}'.format(instance.name + ' ' + instance.family, filename)
class Main(models.Model):
    name = models.CharField(max_length=64, blank=False)
    family = models.CharField(max_length=126, blank=False)

    field = models.CharField(max_length=256, blank=True)
    university = models.CharField(max_length=256, blank=True)
    title = models.CharField(max_length=125, blank=True)
    doctor_adviser = models.CharField(max_length=125, blank=True)

    money = models.IntegerField()
    debt_payment1 = models.FileField(upload_to=user_directory_path, blank=True)
    debt_payment2 = models.FileField(upload_to=user_directory_path, blank=True)
    debt_payment3 = models.FileField(upload_to=user_directory_path, blank=True)

    start_date = models.DateField()

    proposal = models.FileField(upload_to=user_directory_path, blank=True)
    ch123 = models.FileField(upload_to=user_directory_path, blank=True)
    ch45 = models.FileField(upload_to=user_directory_path, blank=True)

    translation = models.FileField(upload_to=user_directory_path, blank=True)
    # research assistant code 
    RAC = models.CharField(max_length=64, blank=True)
    representative = models.CharField(max_length=64, blank=True)
    description = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.name) + ' ' + str(self.family)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})
    class Meta:
        unique_together = ('name', 'family',)

class TODO(models.Model):
    title = models.CharField(max_length=64)
    # zremind is that remind for order_by i must to rename that
    status = models.CharField(max_length=16, choices=[('today', 'امروز'), ('necessary', 'ضروروی'), ('zremind', 'یادآوری'),])
    remind_datetime = models.DateTimeField(blank=True, default=timezone.now)
    done = models.BooleanField(default=False)
    description = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.title)

main/forms.py
from django import forms 

class AddPeopleForm(forms.Form):
    name= forms.CharField(max_length=126, label='اسم', required=True)
    family = forms.CharField(max_length=126, label='فامیلی', required=True)

    field = forms.CharField(max_length=256, label='رشته', required=False)
    university = forms.CharField(max_length=126, label='دانشگاه', required=False)
    title= forms.CharField(max_length=256, label='عنوان', required=False)
    doctor_adviser = forms.CharField(max_length=126, label='استاد راهنما', required=False)

    money = forms.IntegerField(label='پول', required=True)
    debt_payment1 = forms.FileField(max_length=126, label='قسط اول', required=False)
    debt_payment2 = forms.FileField(max_length=126, label='قسط دوم', required=False)
    debt_payment3 = forms.FileField(max_length=126, label='قسط سوم', required=False)

    start_date = forms.DateField(label='شروع کار', required=False)

    proposal = forms.FileField(label='پروپوزال', required=False)
    ch123 = forms.FileField(label='فصل 1 تا 3', required=False)
    ch45 = forms.FileField(label='فصل 4 و 5', required=False)

    translation = forms.CharField(max_length=126, label='ترجمه', required=False)
    RAC = forms.CharField(max_length=126, label='کد رهگیری پژوهشیار', required=False)
    representative = forms.CharField(max_length=126, label='معرف', required=False)
    description = forms.CharField(label='توضیحات', widget=forms.Textarea, required=False)

class AddTODOForm(forms.Form):
    CHOICES = [('today', 'امروز'), ('necessary', 'ضروروی'), ('zremind', 'یادآوری')]
    title = forms.CharField(max_length=126, label='عنوان')
    status = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    description = forms.CharField(widget=forms.Textarea, required=False)
    remind_datetime = forms.DateTimeField(required=False)

class Updata(forms.Form):
    text = forms.CharField(max_length=256, required=False)
    file = forms.FileField(required=False)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Main, TODO
from .forms import AddPeopleForm, AddTODOForm, Updata



def home(request):
    main_objects = Main.objects.all()
    if request.method == "POST":
        if request.POST.get("todo", None):
            pk_todo = request.POST.get("todo", '')
            TODO.objects.filter(pk=pk_todo).update(done=True)
        elif request.POST.get("delete", None):
           pk_delete = request.POST.get("delete", None)
           TODO.objects.get(pk=pk_delete).delete()
        elif request.POST.get("delete-main", None):
           pk_delete = request.POST.get("delete-main", None)
           Main.objects.get(pk=pk_delete).delete()

    todo_objects = TODO.objects.filter(done=False).order_by('status')
    job_dones = TODO.objects.filter(done=True).order_by('status')
    context = {
        'main_objects': main_objects,
        'todo_objects': todo_objects,
        'job_dones': job_dones,
    }
            
    return render(request, 'home.html', context=context)

def detail(request, pk):
    if request.method == "POST":
        form = Updata(request.POST, request.FILES)
        if form.is_valid():
            if len(request.POST) == 3:
                if request.POST.get("field", None):
                    field = request.POST.get("field", None)
                    Main.objects.filter(pk=pk).update(field=field)
                elif request.POST.get("university", None):
                    university = request.POST.get("university", None)
                    Main.objects.filter(pk=pk).update(university=university)
                elif request.POST.get("doctor_adviser", None):
                    doctor_adviser = request.POST.get("doctor_adviser", None)
                    Main.objects.filter(pk=pk).update(doctor_adviser=doctor_adviser)
                elif request.POST.get("title", None):
                    title = request.POST.get("title", None)
                    Main.objects.filter(pk=pk).update(title=title)
                elif request.POST.get("rac", None):
                    rac = request.POST.get("rac", None)
                    Main.objects.filter(pk=pk).update(RAC=rac)
                elif request.POST.get("representative", None):
                    representative = request.POST.get("representative", None)
                    Main.objects.filter(pk=pk).update(representative=representative)
            if len(request.FILES) == 1:
                query = Main.objects.get(pk=pk)
                if request.FILES.get("debt_payment1", None):
                    # update(request.FILES.get("debt_payment1", None), name, family)
                    query.debt_payment1 = request.FILES['debt_payment1']
                    query.save()
                elif request.FILES.get("debt_payment2", None):
                    query.debt_payment2 = request.FILES['debt_payment2']
                    query.save()
                elif request.FILES.get("debt_payment3", None):
                    query.debt_payment3 = request.FILES['debt_payment3']
                    query.save()
                elif request.FILES.get("proposal", None):
                    query.proposal = request.FILES['proposal']
                    query.save()
                elif request.FILES.get("ch123", None):
                    query.ch123 = request.FILES['ch123']
                    query.save()
                elif request.FILES.get("ch45", None):
                    query.ch45 = request.FILES['ch45']
                    query.save()
            
    people_detail = get_object_or_404(Main, pk=pk)
    return render(request, 'detail.html', {'people': people_detail})

def add_people(request):
    if request.method == "POST":

        form = AddPeopleForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            family = form.cleaned_data['family']
            field = form.cleaned_data['field']
            university = form.cleaned_data['university']
            title  = form.cleaned_data['title']
            doctor_adviser = form.cleaned_data['doctor_adviser']
            money = form.cleaned_data['money']
            debt_payment1 = request.FILES.get("debt_payment1")
            debt_payment2 = request.FILES.get("debt_payment2")
            debt_payment3 = request.FILES.get("debt_payment3")
            start_date = form.cleaned_data['start_date']
            if not start_date:
                start_date = timezone.now()
            proposal = form.cleaned_data['proposal']
            ch123 = form.cleaned_data['ch123']
            ch45 = form.cleaned_data['ch45']
            translation = request.FILES.get("translation")
            rac = form.cleaned_data['RAC']
            representative = form.cleaned_data['representative']
            description = form.cleaned_data['description']
            main_object = Main.objects.create(
                                name=name,
                                family=family,
                                field=field,
                                university=university,
                                title=title,
                                doctor_adviser=doctor_adviser,
                                money=money,
                                debt_payment1=debt_payment1,
                                debt_payment2=debt_payment2,
                                debt_payment3=debt_payment3,
                                start_date=start_date,
                                proposal=proposal,
                                ch123=ch123,
                                ch45=ch45,
                                translation=translation,
                                RAC=rac,
                                representative=representative,
                                description=description,
                            )
            main_object.save()
            return redirect('/')
    else:
        form = AddPeopleForm()
    return render(request, 'add_people.html', {'form': form})

def add_todo(request):
    if request.method == 'POST':
        form = AddTODOForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            status = form.cleaned_data['status']
            if status == 'zremind':
                remind_datetime = form.cleaned_data['remind_datetime']
            else:
                remind_datetime = timezone.now()
            description = form.cleaned_data['description']
            todo = TODO.objects.create(title=title, 
                                       status=status, 
                                       description=description, 
                                       remind_datetime=remind_datetime
                                       )
            todo.save()
            return redirect('/')
    else:
        form = AddTODOForm()
    return render(request, 'add_todo.html', {'form': form})

def todos_page(request):
    if request.method == "POST":
        if request.POST.get("todo", None):
            pk_todo = request.POST.get("todo", '')
            TODO.objects.filter(pk=pk_todo).update(done=True)
        if request.POST.get("delete", None):
           pk_delete = request.POST.get("delete", None)
           TODO.objects.get(pk=pk_delete).delete()
           
    todaies = TODO.objects.filter(status='today', done=False)
    necessaries = TODO.objects.filter(status='necessary', done=False)
    reminds = TODO.objects.filter(status='zremind', done=False).order_by('remind_datetime')
    return render(request, 'todos_page.html', {'todaies': todaies, 'necessaries': necessaries, 'reminds': reminds})

main/templates/add_people.html
{% extends 'base.html' %}
{% block title %}
    فرم پر کردن فرد جدید
{% endblock title %}

{% block style %}
    .container{
        direction: rtl;
    }
{% endblock style %}

{% block body %}
{% if user.is_superuser %}
    
    <div class="container bg-light shadow-sm p-3 rounded">
        <div class="row g-3">
            <div class="col-md-6 col-lg-8 mx-auto">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-name"> نام </lable>
                            <input class="form-control" id="input-name" name="name" type="text" placeholder value required>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-family"> نام فامیلی </lable>
                            <input class="form-control" id="input-family" name="family" type="text" placeholder value required>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-field"> رشته </lable>
                            <input class="form-control m-1" id="input-field" name="field" type="text" placeholder value>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-university"> دانشگاه </lable>
                            <input class="form-control m-1" id="input-university" name="university" type="text" placeholder value>
                        </div>
                        <div class="col-12"> 
                            <lable class="form-lable p-3" for="input-doctor-adviser"> استاد راهنما </lable>
                            <input class="form-control m-1" id="input-doctor-adviser" name="doctor_adviser" type="text" placeholder value>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-title"> عنوان </lable>
                            <input class="form-control m-1" id="input-title" name="title" type="text" placeholder value>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-money"> پول قرارداد </lable>
                            <input class="form-control m-2" id="input-money" name="money" type="text" placeholder value>
                        </div>
                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-debt_peyment1"> قسط 1 </lable>
                            <input class="form-control m-1" id="input-debt_peyment1" name="debt_payment1" type="file" placeholder value>
                        </div>
                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-debt_peyment2"> قسط 2 </lable>
                            <input class="form-control m-1" id="input-debt_peyment2" name="debt_payment2" type="file" placeholder value>
                        </div>
                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-debt_peyment3"> قسط 3 </lable>
                            <input class="form-control m-2" id="input-debt_peyment3" name="debt_payment3" type="file" placeholder value>
                        </div>

                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-start-date"> تاریخ شروع کار </lable>
                            <input class="form-control m-2" id="input-start-date" name="start_date" type="datetime-local">
                        </div>

                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-translation"> ترجمه </lable>
                            <input class="form-control m-2" id="input-translation" name="translation" type="file" placeholder value>
                        </div>

                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-proposal"> پروپوزال </lable>
                            <input class="form-control m-1" id="input-proposal" name="proposal" type="file" placeholder value>
                        </div>
                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-ch123"> فصل 1 تا 3</lable>
                            <input class="form-control m-1" id="input-ch123" name="ch123" type="file" placeholder value>
                        </div>
                        <div class="col-md-4"> 
                            <lable class="form-lable p-3" for="input-ch45"> فصل 4 و 5</lable>
                            <input class="form-control m-2" id="input-ch45" name="ch45" type="file" placeholder value>
                        </div>
                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-rac"> کد رهگیری پژوهشیار </lable>
                            <input class="form-control m-2" id="input-rac" name="RAC" type="text">
                        </div>

                        <div class="col-sm-6"> 
                            <lable class="form-lable p-3" for="input-representative"> معرف </lable>
                            <input class="form-control m-2" id="input-representative" name="representative" type="text" placeholder value>
                        </div>

                        <div class="col-12">
                            <lable class="form-lable p-3" for="input-description"> توضیحات </lable>
                            <textarea class="form-control m-2" id="input-description" name="description" row=3> </textarea>
                        </div>

                        <div class="col-12 d-grid p-2">
                            <input type="submit" class="btn m-2 btn-primary">
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
    {% comment %} <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form> {% endcomment %}
{% else %}
    <h1> Your not register </h1>
{% endif %}
{% endblock body %}

main/templates/add_todo.html
{% extends 'base.html' %}
{% block title %}
فرم پر کردن کار ها
{% endblock title %}
{% block style %}
    
#title-input, #id_description{
    direction: rtl;
}
    
{% endblock style %}

{% block body %}
{% if user.is_superuser %}
   <form  method="POST">
        {% csrf_token %}
        <div class="container p-3"> 
           <div class="row p-3 ">
                <div class="col-lg-9 mx-auto shadow-lg rounded bg-light p-3"> 
                    <div class="p-3">
                        <div class="text-end ">
                            <label class="form-label me-3 " for="title-input"> کار </label><br>
                            <input class="form-control  mb-3" type="text" id="title-input" name="title" required >
                        </div>

                        <dev class="mbt-3"> 
                          
                            <div class="form-check mt-2 ">
                                <input class="form-check-input" type="radio" name="status" value="today" id="id_status_0" checked required>
                                <label class="form-check-label" for="id_status_0">
                                    امروز
                                </label>
                            </div>
                            <div class="form-check mt-2">
                                <input class="form-check-input" type="radio" name="status" value="necessary" id="id_status_1" required>
                                <label class="form-check-label" for="id_status_1">
                                    ضروری
                                </label>
                            </div>
                            <div class="form-check mt-2">
                                <input class="form-check-input" type="radio" name="status" value="zremind" id="id_status_2" required>
                                <label class="form-check-label" for="id_status_2">
                                    یادآوری
                                </label>
                                <script>
                                        if (document.getElementById("id_status_2").checked == true){
                                            alert("hello");
                                            {% comment %} https://stackoverflow.com/questions/43050218/how-to-check-contents-of-input-in-real-time {% endcomment %}
                                        };
                                </script>
                                <input class="ms-3" type="datetime-local" name="remind_datetime" id="datetime_picker">
                            </div>
                        </dev>
                        <div class="text-end">
                            <label for="id_description" class="form-label mt-3"> توضیحات </label>
                            <textarea class="form-control " name="description" id="id_description" rows="3"></textarea> 
                        </div>

                    </div>
                    <div class="d-grid gap-2">
                        <input type="submit" value="ثبت" class="btn btn-primary m-3">
                        <a href="/" class="btn btn-primary mx-3"><i class="bx bx-arrow-back bx-sm"></i></a>
                    </div>
                </div>
            </dev>
        </div>
    </form>

{% else %}
    <h1> Your not register </h1>
{% endif %}
{% endblock body %}

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>{% block style %}{% endblock style %}</style> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    {% block head %}{% endblock head %}
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>

main/templates/home.html
{% extends 'base.html' %}
{% block title %}
    خانه
{% endblock title %}
{% block style %}
        body{
            background-color: gray;
        }
        .text-decoration-none: hover{
            direction: underline;
        }
        .trash-icon-button{
            border: none;
            background: none;
        }
        .container{
            background-color: #9e9a90;
        }
        .trash-icon{
            color: #be4d25;
            cursor: pointer;
        }

        .list-group-item {
            direction: rtl;
        }

        h3{
           color: black;
        }    

        .list-group{
            max-height: 20rem;
        }
        .telegram{
            color: #229ED9;
        }
        .whatsapp{
            color: #075e54;
        }
{% endblock style%}
 
{% block body %}
{% if user.is_superuser %}
    <div class="container content-row px-3 pt-3">
        <div class="row ">
            <div class="col-md-12 col-lg-6">
                <h3 class="text-center"> اسامی </h3>
                <div class="card overflow-auto ">
                    <form method="post" id="main-form" onsubmit="return validation();">
                        {% csrf_token %}
                        <ol class="list-group list-group-numbered">
                            {% for main in main_objects %}
                                    <a href="{{main.get_absolute_url}}" class="text-decoration-none list-group-item list-group-item-action"> 
                                       {{ main.name }} {{ main.family }}
                                            <button class="px-2 py-1 bx bxs-trash bx-tada-hover trash-icon-button trash-icon-button-main trash-icon float-start" name="delete-main" value="{{ main.pk }}"></button>
                                    </a>
                            {% endfor %}
                        </ol>
                    </form>

                </div>
                    <div class="text-center p-2"> 
                        <a class="btn btn-primary text-center" href="add-people/" role="button"><i class="bx bx-plus bx-sm"></i></a> 
                    </div>

                
            </div>
            <div class="col-md-12 col-lg-6 p-3">
			<h3 class="text-center"> کارها </h3> 
                <div class="card  overflow-auto">
                        <ol class="list-group list-group-numbered">
                            <form method="post" id="todo-form" onsubmit="return validation();">
                                {% csrf_token %}
                                {% for todo in todo_objects %}
                                        {% if todo.status == "necessary" %}
                                            {% comment %} <button type="button" class="list-group-item list-group-item-danger list-group-item-action"> {{ forloop.counter }}.{{ todo.title }} {% endcomment %}
                                            <div  class="list-group-item list-group-item-danger list-group-item-action"> {{ forloop.counter }}.{{ todo.title }}

                                                <input class="form-check-input float-start shadow-sm rounded bg-info form-check-answer" type="checkbox" name="todo" value="{{todo.pk}}" id="checkboxlabel">
                                                <button class="px-2 py-1 bx bxs-trash bx-tada-hover trash-icon-button trash-icon float-start" name="delete" value="{{ todo.pk }}"></button>
                                            </div>
                                        {% elif todo.status == "today" %}
                                            <div class="list-group-item list-group-item-secondary list-group-item-action"> {{ forloop.counter }}.{{ todo.title }} 
                                                <input class="form-check-input float-start shadow-sm rounded bg-info form-check-answer" type="checkbox" name="todo" value="{{ todo.pk }}" id="checkboxlabel">
                                                <button class="px-2 py-1 bx bxs-trash bx-tada-hover trash-icon-button trash-icon float-start" name="delete" value="{{ todo.pk }}"></button>
                                                
                                            </div>
                                        {% else %}
                                            <div class="list-group-item list-group-item-action"> {{ forloop.counter }}.{{ todo.title }} 
                                                <input class="form-check-input float-start shadow-sm rounded bg-info form-check-answer" type="checkbox" name="todo" value="{{ todo.pk }} " id="checkboxlabel">
                                                <button class="px-2 py-1 bx bxs-trash bx-tada-hover trash-icon-button trash-icon float-start" name="delete" value="{{ todo.pk }}"></button>
                                            </div>
                                    {% endif %}
                                {% endfor %}
                            </form>
                        </ol>
                </div>
                        <div class="text-center p-2"> 
                            <a class="btn btn-primary text-center" href="add-todo/" role="button"><i class="bx bx-plus bx-sm"></i></a> 
                            <a class="btn btn-primary text-center" href="todos-page/" role="button"><i class="bx bx-expand bx-sm"></i></a> 
                        </div>
                    
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-6 mx-auto p-2 m-2">
            <h3 class="text-center"> کارهای انجام شده </h3> 
                            <div class="card  overflow-auto">
                                    <ol class="list-group list-group-numbered">
                                            {% for job  in job_dones %}
                                                    {% if job.status == "necessary" %}
                                                        <div  class="list-group-item list-group-item-danger list-group-item-action"> {{ job.title }}
                                                        </div>
                                                    {% elif job.status == "today" %}
                                                        <div class="list-group-item list-group-item-secondary list-group-item-action"> {{ job.title }} 
                                                        </div>
                                                    {% else %}
                                                        <div class="list-group-item list-group-item-action"> {{ job.title }} 
                                                        </div>
                                                {% endif %}
                                            {% endfor %}
                                    </ol>
                            </div>
                                    
                                
                        </div>



            </div>

        </div>
    </div>
    <script>
        const x = document.getElementsByClassName("trash-icon");
        const formDelete = document.getElementById("todo-form");
        for (var i = 0; i < x.length; i++){
            x[i].addEventListener("click", validation());
        }
    </script>
    <script> 
        const y = document.getElementsByClassName("form-check-answer");
        const formDone = document.getElementById("todo-form");
        for (var i = 0; i < y.length; i++)
            y[i].addEventListener("click", function(){
                formDone.submit();

            });
        </script>
   
    <script> 
        const y = document.getElementsByClassName("trash-icon");
        const formDone = document.getElementById("main-form");
        for (var i = 0; i < y.length; i++)
            y[i].addEventListener("click", function(){
                formDone.submit();

            });
        </script>

        <script> 
            function validation()
            {
                if (window.confirm("برای حذف مطمئن هستید؟"))
                    return true;
                return false;
                    
            }
        </script>


{% else %}
    <h1> your not register </h1>
{% endif %}
{% endblock body %}       